### ISSUE TITLE
script error :: shortURL API

### ISSUE THREAD

**Issue by NaviFly** [naver/naver-openapi-guide#9]
단축 URL API 예제중 PHP 예제 잘못 표기
 $url = "https://openapi.naver.com/v1/util/shorturl?url=" + $encText ;

 $url = "https://openapi.naver.com/v1/util/shorturl?url=" . $encText ;
로 수정 요청

**Comment by benelog** [comment]
https://github.com/naver/naver-openapi-guide/commit/a09790113e7e4e2db3a2039a9ceea7be3abdafd1 으로 반영되었던 건이네요.
